### ISSUE TITLE
Try an OpenHack night with the group.

### ISSUE THREAD

**Issue by abargnesi** [haverhillhackers/suggestions#1]
We should get together and right some code. The format for this type of meetup session could be [OpenHack](http://openhack.github.io/#how-does-openhack-work).

Basicallly the format is:
- Enjoy Food / Beverages.
- Introductions (every night).
  - Who are you?
  - What would you like to work on?
- Self-organize into groups or on your own.
- Hack on whatever you want.
- Optionally, share something to the group at the end of the night.

Rough schedule:

_6:15pm_ - _6:30pm_
Food / Beverage

_6:30pm_
Introductions

_6:45pm_
Organize and hack

_9:00pm_
Share to the group

**Comment by johnnadeau** [comment]
This is great. 

Some thoughts:
- We can have this on a separate day of the week than our other meetings (Wednesday currently)
- We should have a guiding topic or aim of the night (example: use the Gitter API to interact with our chatroom)
- Do we need to limit the attendance on these nights? In the current space we can probably support about 10-12 people comfortably at the tables at the hackspace.

**Comment by abargnesi** [comment]
Yeah, how about Thursday? If there was a talk given the day before people can try out some of their own ideas.

In terms of what people want to work on, it might work better if it was more organic. For example you and some other people may want to work with the Gitter API. Others may want to work on some other ideas, or even just learn and talk to others.

I would think we would want a limit so that the space is comfortable. We could probably fit a bit more by leveraging @coreymasson table layout skills.

**Comment by abargnesi** [comment]
I'm thinking about February 25th for this. I'll make a final proposal and send it to the meetup group.

**Comment by johnnadeau** [comment]
:+1:

**Comment by abargnesi** [comment]
@johnnadeau Scheduled the openhack meetup. [Take a look](http://www.meetup.com/HaverhillHackers/events/228664826/) and let me know what you think.

**Comment by johnnadeau** [comment]
@abargnesi Looks good to me. I'd say just start it at 6:00PM for these events.

**Comment by johnnadeau** [comment]
Also, the name of the meetup should obviously be **Open Haverhill Hack** :smile:

**Comment by abargnesi** [comment]
Ok thanks the title change is pretty sweet, :clap:

I changed the time to 6pm as well.

We can close this now I guess.

**Comment by abargnesi** [comment]
Thanks to @d0nkeyBOB and @johnnadeau we are up on http://openhack.github.io/.

:mega:
